use_frameworks!

target 'GRTextField_Example' do
  pod 'GRTextField', :path => '../'

  target 'GRTextField_Tests' do
    inherit! :search_paths
    pod 'Nimble', '~> 7.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
